/**
 * AgentForEach Infrastructure — Azure Web PubSub
 *
 * Provisions the managed WebSocket service for real-time communication
 * between AgentForEach's serverless backend and clients (iOS, Android, Web).
 *
 * Architecture:
 *   - Azure Functions push events via the server SDK (@azure/web-pubsub)
 *   - Clients connect via native WebSocket using a short-lived access token
 *   - Hub "agentforeach" routes all events (cron results, chat, presence)
 *   - User-targeted delivery via sendToUser() (userId = AgentForEach user ID)
 *   - Group-based broadcast via groups (e.g., "cron", "chat", "admin")
 *
 * A fully managed service: no persistent WebSocket server process.
 */

import * as webpubsub from "@pulumi/azure-native/webpubsub";
import * as pulumi from "@pulumi/pulumi";

// ============================================================================
// Web PubSub Service
// ============================================================================

/**
 * Create the Azure Web PubSub service instance.
 *
 * Standard_S1 by default: each unit takes 1,000 concurrent connections and
 * 1M messages a day (more are billed), and units scale up to 100. Free_F1
 * (20 connections, 20k messages a day) is only for trying things out.
 */
export function createWebPubSub(args: {
  resourceGroupName: pulumi.Input<string>;
  location: pulumi.Input<string>;
  resourceName: string;
  sku: "Free_F1" | "Standard_S1" | "Premium_P1";
  units: number;
  tags: Record<string, string>;
}) {
  return new webpubsub.WebPubSub(args.resourceName, {
    resourceName: args.resourceName,
    resourceGroupName: args.resourceGroupName,
    location: args.location,
    sku: {
      name: args.sku,
      tier: args.sku.split("_")[0],
      capacity: args.sku === "Free_F1" ? 1 : args.units,
    },
    // Access keys stay on: the runtime signs client tokens and verifies
    // upstream ce-signature with them. Entra ID auth is allowed as well.
    disableAadAuth: false,
    disableLocalAuth: false,
    // TLS 1.2 minimum
    tls: {
      clientCertEnabled: false,
    },
    tags: args.tags,
  });
}

// ============================================================================
// Hub
// ============================================================================

/**
 * Create the "agentforeach" hub within the Web PubSub service.
 *
 * Hubs are logical namespaces. All AgentForEach real-time events flow through
 * this single hub, with groups for topic-based routing.
 *
 * Anonymous connections are denied — clients must authenticate via
 * access tokens generated by the server.
 */
export function createWebPubSubHub(args: {
  resourceGroupName: pulumi.Input<string>;
  webPubSubName: pulumi.Input<string>;
  hubName: string;
  /** Base URL of the Function App (e.g., https://<your-function-app>.azurewebsites.net) */
  functionAppUrl: pulumi.Input<string>;
}) {
  // No secret in the URL (it would land in access logs): Web PubSub signs
  // each upstream call with ce-signature, which the handlers verify with the
  // access key from WEBPUBSUB_CONNECTION_STRING.
  //
  // Handlers are matched in order and the first match wins, so only the
  // message handler takes user events.
  const connectUrl = pulumi.interpolate`${args.functionAppUrl}/ws/connect`;
  const messageUrl = pulumi.interpolate`${args.functionAppUrl}/ws/message`;
  const disconnectUrl = pulumi.interpolate`${args.functionAppUrl}/ws/disconnected`;

  return new webpubsub.WebPubSubHub(args.hubName, {
    hubName: args.hubName,
    resourceGroupName: args.resourceGroupName,
    resourceName: args.webPubSubName,
    properties: {
      anonymousConnectPolicy: "deny",
      eventHandlers: [
        {
          urlTemplate: connectUrl,
          systemEvents: ["connect"],
          auth: {
            type: "None",
          },
        },
        {
          urlTemplate: messageUrl,
          userEventPattern: "*",
          systemEvents: [],
          auth: {
            type: "None",
          },
        },
        {
          urlTemplate: disconnectUrl,
          systemEvents: ["disconnected"],
          auth: {
            type: "None",
          },
        },
      ],
    },
  });
}

// ============================================================================
// Connection String (secret)
// ============================================================================

/**
 * Retrieve the primary connection string for the Web PubSub service.
 * Used by the server SDK to send events and generate client tokens.
 */
export function getWebPubSubConnectionString(args: {
  resourceGroupName: pulumi.Input<string>;
  resourceName: pulumi.Input<string>;
}): pulumi.Output<string> {
  const connStr = pulumi
    .all([args.resourceGroupName, args.resourceName])
    .apply(async ([rg, name]) => {
      const keys = await webpubsub.listWebPubSubKeys({
        resourceGroupName: rg,
        resourceName: name,
      });
      return keys.primaryConnectionString ?? "";
    });

  return pulumi.secret(connStr);
}

/**
 * The secondary access key. Web PubSub signs upstream calls with both keys,
 * so the runtime keeps verifying while the primary is regenerated.
 */
export function getWebPubSubSecondaryKey(args: {
  resourceGroupName: pulumi.Input<string>;
  resourceName: pulumi.Input<string>;
}): pulumi.Output<string> {
  return pulumi.secret(
    pulumi.all([args.resourceGroupName, args.resourceName]).apply(async ([rg, name]) => {
      const keys = await webpubsub.listWebPubSubKeys({ resourceGroupName: rg, resourceName: name });
      return keys.secondaryKey ?? "";
    }),
  );
}
