#!/usr/bin/env node
/**
 * Writes a deployment's Wrangler config from the checked-in one.
 *
 * deploy/cloudflare/wrangler.jsonc holds what every deployment shares; a
 * deployment's own values (its Hyperdrive id, R2 endpoint, public URL, its
 * agentforeach.json) go into deploy/cloudflare/wrangler.generated.jsonc,
 * which is git-ignored. It sits next to the checked-in file, so `main` and
 * the aliases resolve the same way. Then:
 *
 *   npx wrangler dev    --config deploy/cloudflare/wrangler.generated.jsonc
 *   npx wrangler deploy --config deploy/cloudflare/wrangler.generated.jsonc
 *
 * (A config file is the one way both commands agree on: `wrangler dev`
 * ignores a CLI --alias for a module the config already aliases.)
 *
 *   node scripts/cloudflare-config.mjs \
 *     [--name agentforeach] \
 *     [--config-file path/to/agentforeach.json] \
 *     [--hyperdrive-id <id>] \
 *     [--no-containers] \
 *     [--image-var KEY=VALUE ...] \
 *     [--var KEY=VALUE ...]
 *
 * --no-containers leaves out the sandbox container (for a config with
 * sandboxes off), so a deploy doesn't build and push its image.
 * --image-var passes a build variable to the sandbox image's Dockerfile
 * (SANDBOX_IMAGE_BROWSER=1 for the browser).
 * --config-file is relative to the current directory. --var sets plain
 * vars; secrets go through `wrangler secret put` (or .dev.vars locally).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const deployDir = join(root, "deploy/cloudflare");
const base = join(deployDir, "wrangler.jsonc");
const out = join(deployDir, "wrangler.generated.jsonc");

/** wrangler.jsonc, comments and trailing commas removed. */
export function readJsonc(path) {
  const text = readFileSync(path, "utf8")
    .replace(/("(?:[^"\\]|\\.)*")|\/\/[^\n]*|\/\*[\s\S]*?\*\//g, (_m, string) => string ?? "")
    .replace(/,(\s*[}\]])/g, "$1");
  return JSON.parse(text);
}

function parseArgs(argv) {
  const opts = { vars: {} };
  for (let i = 2; i < argv.length; i++) {
    const flag = argv[i];
    if (flag === "--no-containers") {
      opts.noContainers = true;
      continue;
    }
    const value = argv[++i];
    if (value === undefined) throw new Error(`${flag} needs a value`);
    if (flag === "--name") opts.name = value;
    else if (flag === "--config-file") opts.configFile = value;
    else if (flag === "--hyperdrive-id") opts.hyperdriveId = value;
    else if (flag === "--image-var") {
      const eq = value?.indexOf("=") ?? -1;
      if (eq < 1) throw new Error(`--image-var takes KEY=VALUE, got ${value}`);
      opts.imageVars = { ...opts.imageVars, [value.slice(0, eq)]: value.slice(eq + 1) };
    }
    else if (flag === "--var") {
      const eq = value.indexOf("=");
      if (eq < 1) throw new Error(`--var takes KEY=VALUE, got ${value}`);
      opts.vars[value.slice(0, eq)] = value.slice(eq + 1);
    } else throw new Error(`unknown option ${flag}`);
  }
  return opts;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const opts = parseArgs(process.argv);
  const config = readJsonc(base);
  if (opts.name) config.name = opts.name;
  if (opts.configFile) {
    const target = relative(deployDir, resolve(process.cwd(), opts.configFile));
    config.alias = { ...config.alias, "@agentforeach/config": target.startsWith(".") ? target : `./${target}` };
  }
  if (opts.hyperdriveId) {
    config.hyperdrive = (config.hyperdrive ?? []).map((h) => (h.binding === "HYPERDRIVE" ? { ...h, id: opts.hyperdriveId } : h));
  }
  // The Durable Object class stays bound (its migration is part of every
  // deployment); only the container image is left out.
  if (opts.noContainers) delete config.containers;
  else if (opts.imageVars) {
    config.containers = (config.containers ?? []).map((c) => ({
      ...c,
      images: Object.fromEntries(
        Object.entries(c.images ?? {}).map(([name, image]) => [
          name,
          "dockerfile" in image ? { ...image, build_vars: { ...image.build_vars, ...opts.imageVars } } : image,
        ]),
      ),
    }));
  }
  config.vars = { ...config.vars, ...opts.vars };
  writeFileSync(
    out,
    `// Generated by scripts/cloudflare-config.mjs from wrangler.jsonc; git-ignored. Don't edit: regenerate.\n` +
      `${JSON.stringify(config, null, 2)}\n`,
  );
  console.log(`wrote ${relative(process.cwd(), out)}`);
}
